/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 12a6
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (9) - Copy.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 330));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel3.setText("<HTML> \t<HEAD> \t\t<TITLE> \t\t\tMY FIRST HTML PAGE \t\t</TITLE> \t</HEAD> \t<A HREF=\"SECOND PAGE.HTML\"> \tSECOND PAGE</A> \t<BODY background=\"C:\\Users\\12a6\\Desktop\\HTML\\1234.jpg\"> \t\t<CENTER> \t\t\t<H1> \t\t\t\t<U> \t\t\t\t\tCLASS XII \t\t\t\t</U> \t\t\t</H1> \t\t \t\tABOUT MYSELF: \t\t<HR> \t\t\t<P> \t\t\t\t<FONT SIZE=\"7\" COLOR=\"RED\">  \t\t\t\t\t\t\t \t\t\t\t\t\t\t\tNAME: \t\t\t\t\t\t\t \t\t\t\t</FONT> \t\t\t\t<FONT SIZE=\"5\" COLOR=\"BLUE\"> \t\t\t\t\t\t\t<U> \t\t\t\t\t\t\t\t<I>\t \t\t\t\t\t\t\t\t LAKSHYA \t\t\t\t\t\t\t\t</I> \t\t\t\t\t\t\t</U> \t\t\t\t</FONT> \t\t\t<P> \t\t\t\t<FONT SIZE=\"7\" COLOR=\"RED\">  \t\t\t\t\t\t\t \t\t\t\t\t\t\t\tAGE: \t\t\t\t\t\t\t \t\t\t\t</FONT> \t\t\t\t<FONT SIZE=\"5\" COLOR=\"BLUE\"> \t\t\t\t\t\t\t<U> \t\t\t\t\t\t\t\t<I>\t \t\t\t\t\t\t\t\t 17 \t\t\t\t\t\t\t\t</I> \t\t\t\t\t\t\t</U> \t\t\t\t</FONT> \t\t\t<p> \t\t\t\t<IMG src=\"C:\\Users\\12a6\\Desktop\\HTML\\123.JPG\" WIDTH=\"400px\"> <TABLE BORDER=5> \t<TR> \t<TD> \t\tSUBJECT \t<TD> \t\tSCIENCE \t<TD> \t\tENGLISH\t \t<TD> \t\tHINDI \t<TD> \t\tSOCIAL SCIENCE \t<TD> \t\tMATHS \t<TR> \t<TD> \t\tMARKS \t<TD> \t\t90 \t<TD>\t\t \t\t90 \t<TD>\t\t \t\t90 \t<TD>\t\t \t\t90 \t<TD>\t\t \t\t90 \t </TABLE>    \t\t<HR>  </CENTER> \t</BODY> </HTML>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 490, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
